export const POSITION_LEFT_WING = 1
export const POSITION_CENTER = 2
export const POSITION_RIGHT_WING = 3
export const POSITION_LEFT_DEFENDER = 4
export const POSITION_RIGHT_DEFENDER = 5
export const POSITION_GOALKEEPER = 999
export const POSITION_OTHER = 1000

export const POSITION_STRINGS = {
  [POSITION_LEFT_WING]: 'VH',
  [POSITION_CENTER]: 'KH',
  [POSITION_RIGHT_WING]: 'OH',
  [POSITION_LEFT_DEFENDER]: 'VP',
  [POSITION_RIGHT_DEFENDER]: 'OP',
  [POSITION_GOALKEEPER]: 'MV',
  [POSITION_OTHER]: 'MUU'
}