export const TOGGLE_PLAYER = 'TOGGLE_PLAYER'
export const RESET_PLAYERS = 'RESET_PLAYERS'
export const GENERATE_LINEUP = 'GENERATE_LINEUP'
export const GENERATE_LINEUP_DURATION_IN_MS = 750
export const RESET_LINEUP = 'RESET_LINEUP'
