export const TOGGLE_PLAYER = 'TOGGLE_PLAYER'
export const GENERATE_LINEUP = 'GENERATE_LINEUP'
export const GENERATE_LINEUP_STATUS = 'GENERATE_LINEUP_STATUS'
export const REQUEST_GENERATE_LINEUP = `REQUEST_${GENERATE_LINEUP}`
export const RECEIVE_GENERATE_LINEUP = `RECEIVE_${GENERATE_LINEUP}`
export const GENERATE_LINEUP_DURATION_IN_MS = 250
