export const TOGGLE_PLAYER = 'TOGGLE_PLAYER'
export const RESET_PLAYERS = 'RESET_PLAYERS'

export const GENERATE_LINEUP = 'GENERATE_LINEUP'
export const GENERATE_LINEUP_DURATION_IN_MS = 750

export const RESET_LINEUP = 'RESET_LINEUP'

export const ANIMATE_LINEUP_IN = 'ANIMATE_LINEUP_IN'
export const ANIMATE_LINEUP_OUT_START = 'ANIMATE_LINEUP_OUT_START'
export const ANIMATE_LINEUP_OUT_END = 'ANIMATE_LINEUP_OUT_END'
export const LINEUP_SCREEN_STATUS_ANIMATE_OUT = 'LINEUP_SCREEN_STATUS_ANIMATE_OUT'
export const LINEUP_SCREEN_STATUS_HIDDEN = 'LINEUP_SCREEN_STATUS_HIDDEN'
export const LINEUP_SCREEN_STATUS_VISIBLE = 'LINEUP_SCREEN_STATUS_VISIBLE'
export const LINEUP_ANIMATION_DURATION_IN_MS = 350
